Repository hub-datastep/demo-backend, pull requests merged in 2025-03, with the labels that each got.

#301 Mapping Iterations and Results refactor & Orders Events Logs saving fix
  src/controller/order_classification/vysota/order_notification.py
  src/infra/chroma_store.py
  src/migrations/versions/9eb4dc7442e2_status_for_mapping_iterations.py
  src/model/file/utd/multi_entities_pdf_parsing_model.py
  src/model/mapping/mapping_with_parsing_model.py
  src/model/mapping/result/llm_mapping_knowledge_base_model.py
  src/model/mapping/result/mapping_iteration_model.py
  src/model/mapping/result/mapping_result_model.py
  src/model/order_classification/order_get_info.py
  src/scheme/mapping/result/mapping_iteration_scheme.py
  src/scheme/mapping/result/similar_nomenclature_search_scheme.py
  src/util/dates.py
Labels: PROD

#307 fix: background tasks for mapping results KB
  src/model/mapping/result/mapping_result_model.py
Labels: PROD

#312 fix: UTD pdf file parsing
  src/model/file/utd/multi_entities_pdf_parsing_model.py
  src/scheme/file/utd_card_message_scheme.py
Labels: PROD

#315 Messages to Resident in Order Chat
  experiments/cleaning_results_message/__init__.py
  experiments/cleaning_results_message/v1/README.md
  experiments/cleaning_results_message/v1/__init__.py
  experiments/cleaning_results_message/v1/main.py
  experiments/cleaning_results_message/v1/modules/__init__.py
  experiments/cleaning_results_message/v1/modules/chains/__init__.py
  experiments/cleaning_results_message/v1/modules/chains/cleaning_result_message_chain.py
  experiments/cleaning_results_message/v1/modules/constants.py
  experiments/cleaning_results_message/v1/modules/env.py
  experiments/cleaning_results_message/v1/modules/schemas.py
  src/app.py
  src/controller/order_classification/vysota/order_classification_controller.py
  src/controller/order_classification/vysota/order_notification_controller.py
  src/infra/database.py
  src/infra/domyland/__init__.py
  src/infra/domyland/auth.py
  src/infra/domyland/chats.py
  src/infra/domyland/constants.py
  src/infra/domyland/orders.py
  src/infra/llm_clients_credentials.py
  src/llm/chain/cleaning_result_comment/__init__.py
  src/llm/chain/cleaning_result_comment/cleaning_result_message_chain.py
  src/llm/chain/mapping/__init__.py
  src/migrations/versions/7c157a6bbb39_message_templates_in_order_.py
  src/model/order_classification/order_classification_config_model.py
  src/model/order_classification/order_classification_history_model.py
  src/model/order_classification/order_classification_model.py
  src/model/order_notification/__init__.py
  src/model/order_notification/order_notification_logs_model.py
  src/model/order_notification/order_notification_model.py
  src/repository/order_classification/order_classification_history_repository.py
  src/repository/order_notification/__init__.py
  src/repository/order_notification/order_notification_logs_repository.py
  src/scheme/order_classification/order_classification_config_scheme.py
  src/scheme/order_classification/order_classification_scheme.py
  src/scheme/order_notification/__init__.py
  src/scheme/order_notification/order_notification_logs_scheme.py
  src/scheme/order_notification/order_notification_scheme.py
  src/util/json_serializing.py
Labels: PROD

#317 fix: check if event was already processed
  src/model/order_classification/order_classification_model.py
  src/model/order_notification/order_notification_logs_model.py
  src/model/order_notification/order_notification_model.py
  src/repository/order_notification/order_notification_logs_repository.py
Labels: PROD

#321 Refactor Kafka Infra
  .gitignore
  docker-compose.yml
  src/controller/kafka/kafka_controller.py
  src/controller/mapping/mapping_result_controller.py
  src/controller/order_classification/vysota/order_classification_controller.py
  src/infra/domyland/chats.py
  src/infra/env.py
  src/infra/kafka.py
  src/infra/kafka/__init__.py
  src/infra/kafka/brokers.py
  src/infra/kafka/helpers.py
  src/infra/llm_clients_credentials.py
  src/kafka/consumer/mapping_with_parsing.py
  src/kafka/consumer/nsi_fetch.py
  src/kafka/consumer/order_chat_message_sending.py
  src/middleware/kafka_middleware.py
  src/model/mapping/result/mapping_result_model.py
  src/model/order_classification/order_classification_model.py
  src/model/order_notification/order_notification_model.py
  src/scheme/kafka/broker_settings_scheme.py
  src/scheme/kafka/send_message_consumer_scheme.py
  src/util/json_serializing.py
  src/util/path_to_file_or_dir.py
Labels: Ready To Merge

#322 Kafka Infra Refactor & Request for Message to Resident Sending in Kafka for Order Notifications
  .gitignore
  docker-compose.yml
  src/controller/kafka/kafka_controller.py
  src/controller/mapping/mapping_result_controller.py
  src/controller/order_classification/vysota/order_classification_controller.py
  src/infra/domyland/chats.py
  src/infra/env.py
  src/infra/kafka.py
  src/infra/kafka/__init__.py
  src/infra/kafka/brokers.py
  src/infra/kafka/helpers.py
  src/infra/llm_clients_credentials.py
  src/kafka/consumer/mapping_with_parsing.py
  src/kafka/consumer/nsi_fetch.py
  src/kafka/consumer/order_chat_message_sending.py
  src/middleware/kafka_middleware.py
  src/model/mapping/result/mapping_result_model.py
  src/model/order_classification/order_classification_model.py
  src/model/order_notification/order_notification_model.py
  src/scheme/kafka/broker_settings_scheme.py
  src/scheme/kafka/send_message_consumer_scheme.py
  src/util/json_serializing.py
  src/util/path_to_file_or_dir.py
Labels: PROD

#323 fix: order chat message sending logs
  src/kafka/consumer/order_chat_message_sending.py
Labels: PROD

#325 Try fix messages to resident multi-sending
  src/infra/kafka/helpers.py
  src/infra/order_notification.py
  src/kafka/consumer/order_chat_message_sending.py
  src/model/order_notification/order_notification_logs_model.py
  src/model/order_notification/order_notification_model.py
  src/repository/order_notification/order_notification_logs_repository.py
Labels: PROD

#326 fix: order resident query getting
  src/infra/domyland/orders.py
  src/model/order_classification/order_classification_model.py
  src/scheme/order_classification/order_classification_scheme.py
Labels: PROD

#324 SLA responsible users pinging
  .gitignore
  docker-compose.yml
  src/controller/order_classification/vysota/order_classification_controller.py
  src/infra/domyland/chats.py
  src/infra/domyland/constants.py
  src/infra/domyland/orders.py
  src/infra/env.py
  src/infra/order_tracking/__init__.py
  src/infra/order_tracking/action.py
  src/infra/order_tracking/task_status.py
  src/kafka/helpers/telegram_message_helper.py
  src/migrations/env.py
  src/migrations/versions/478f4f152397_orders_tracking_tasks.py
  src/model/order_classification/order_classification_model.py
  src/model/order_notification/order_notification_model.py
  src/model/order_tracking/__init__.py
  src/model/order_tracking/actions/new_order_message.py
  src/model/order_tracking/actions/sla_ping_message.py
  src/model/order_tracking/order_tracking_task_model.py
  src/model/order_tracking/task_tracking_model.py
  src/orders_tasks_tracking.py
  src/repository/order_tracking/__init__.py
  src/repository/order_tracking/order_tracking_task_repository.py
  src/scheme/kafka/__init__.py
  src/scheme/order_classification/order_classification_config_scheme.py
  src/scheme/order_classification/order_classification_scheme.py
  src/scheme/order_notification/order_notification_logs_scheme.py
  src/scheme/order_notification/order_telegram_message_scheme.py
  src/scheme/order_tracking/__init__.py
  src/scheme/order_tracking/order_tracking_task_scheme.py
  src/util/seconds_to_time_str.py
Labels: WIP, Ready To Merge

#329 fix: order tracking task is_completed param default value
  src/repository/order_tracking/order_tracking_task_repository.py
  src/scheme/order_tracking/order_tracking_task_scheme.py
Labels: PROD

#331 fix: temporarily comment out clining order status update logic due to bug
  src/controller/order_classification/vysota/order_notification_controller.py
Labels: PROD
