Repository hub-datastep/demo-backend, pull requests merged in 2025-02, with the labels that each got.

#253 UTD new params parsing
  Dockerfile
  docker-compose.yml
  src/kafka/consumer/mapping_with_parsing.py
  src/kafka/consumer/nsi_fetch.py
  src/model/file/utd/mappings_with_parsed_data_model.py
  src/model/file/utd/multi_entities_pdf_parsing_model.py
  src/model/file/utd/utd_entity_params_parsing.py
  src/model/mapping/mapping_execute_model.py
  src/model/mapping/mapping_with_parsing_model.py
  src/model/mapping/result/mapping_result_model.py
  src/scheme/file/utd_card_message_scheme.py
Labels: Ready To Merge

#254 New UTD params & Materials params & Fix Kafka consumers docker running
  Dockerfile
  docker-compose.yml
  src/kafka/consumer/mapping_with_parsing.py
  src/kafka/consumer/nsi_fetch.py
  src/model/file/utd/mappings_with_parsed_data_model.py
  src/model/file/utd/multi_entities_pdf_parsing_model.py
  src/model/file/utd/utd_entity_params_parsing.py
  src/model/mapping/mapping_execute_model.py
  src/model/mapping/mapping_with_parsing_model.py
  src/model/mapping/result/mapping_result_model.py
  src/scheme/file/utd_card_message_scheme.py
Labels: PROD

#255 fix: utd card input message params
  src/scheme/file/utd_card_message_scheme.py
Labels: PROD

#258 fix: try to fix mapping iteration saving & updating
  src/model/mapping/mapping_with_parsing_model.py
  src/model/mapping/result/mapping_iteration_model.py
  src/model/mapping/result/mapping_result_model.py
  src/repository/mapping/mapping_iteration_repository.py
  src/scheme/mapping/result/mapping_iteration_scheme.py
Labels: PROD

#268 fix: key type
  src/infra/kafka.py
Labels: PROD

#275 fix: hide mapping in kafka
  src/model/mapping/mapping_with_parsing_model.py
Labels: PROD

#276 refactor: parsed params in check-result message
  src/model/file/utd/utd_entity_params_parsing.py
  src/model/mapping/mapping_with_parsing_model.py
Labels: PROD

#281 fix: mapping iteration
  src/model/mapping/result/mapping_result_model.py
Labels: PROD

#284 logs to file
  src/model/order_classification/order_get_info.py
Labels: PROD

#285 Llmapper v1
  poetry.lock
  src/infra/chroma_store.py
  src/infra/database.py
  src/infra/env.py
  src/infra/llm_clients_credentials.py
  src/infra/order_classification_clients_credentials.py
  src/llm/chain/mapping/mapping_chain.py
  src/llm/chain/order_classification_chain.py
  src/llm/chain/order_multi_classification/order_multi_classification_chain.py
  src/llm/chain/order_multi_classification/order_query_summarization.py
  src/model/classifier/classifier_config_model.py
  src/model/file/utd/mappings_with_parsed_data_model.py
  src/model/mapping/llm_mapping_model.py
  src/model/mapping/mapping_with_parsing_model.py
  src/model/mapping/result/mapping_result_model.py
  src/model/used_token/used_token_model.py
  src/scheme/mapping/llm_mapping_scheme.py
  src/scheme/mapping/result/mapping_iteration_scheme.py
  src/scheme/order_classification/order_classification_config_scheme.py
  src/util/json_serializing.py
Labels: WIP

#286 LLMapper V1
  poetry.lock
  src/infra/chroma_store.py
  src/infra/database.py
  src/infra/env.py
  src/infra/llm_clients_credentials.py
  src/infra/order_classification_clients_credentials.py
  src/llm/chain/mapping/mapping_chain.py
  src/llm/chain/order_classification_chain.py
  src/llm/chain/order_multi_classification/order_multi_classification_chain.py
  src/llm/chain/order_multi_classification/order_query_summarization.py
  src/model/classifier/classifier_config_model.py
  src/model/file/utd/mappings_with_parsed_data_model.py
  src/model/mapping/llm_mapping_model.py
  src/model/mapping/mapping_with_parsing_model.py
  src/model/mapping/result/mapping_result_model.py
  src/model/used_token/used_token_model.py
  src/scheme/mapping/llm_mapping_scheme.py
  src/scheme/mapping/result/mapping_iteration_scheme.py
  src/scheme/order_classification/order_classification_config_scheme.py
  src/util/json_serializing.py
Labels: PROD

#298 Save feedback in corrected results
  src/model/mapping/llm_mapping_model.py
  src/model/mapping/result/mapping_result_model.py
  src/scheme/mapping/mapping_scheme.py
  src/scheme/mapping/result/mapping_result_scheme.py
Labels: PROD, Ready To Merge

#300 fix: replace None values with nan in knowledge metadata
  src/model/mapping/result/llm_mapping_knowledge_base_model.py
Labels: PROD
