Repository hub-datastep/demo-backend, pull requests merged in 2025-04, with the labels that each got.

#333 Responsible Users Working Time checking before Telegram Ping-Message
  src/infra/domyland/orders.py
  src/kafka/helpers/__init__.py
  src/model/order_classification/order_classification_model.py
  src/model/order_notification/order_notification_model.py
  src/model/order_tracking/actions/__init__.py
  src/model/order_tracking/actions/new_order_message.py
  src/model/order_tracking/actions/sla_ping_message.py
  src/model/order_tracking/helpers/telegram_chat.py
  src/model/order_tracking/task_tracking_model.py
  src/orders_tasks_tracking.py
  src/repository/order_tracking/order_tracking_task_repository.py
  src/scheme/order_classification/order_classification_config_scheme.py
  src/util/dates.py
  src/util/validation.py
Labels: Ready To Merge

#338 feat: add order data enrichment to send new order message
  src/controller/order_classification/vysota/order_classification_controller.py
  src/infra/domyland/orders.py
  src/model/order_classification/order_classification_config_model.py
  src/model/order_tracking/actions/new_order_message.py
  src/model/order_tracking/actions/sla_ping_message.py
  src/model/order_tracking/helpers/done_actions_count.py
  src/model/order_tracking/task_tracking_model.py
  src/orders_tasks_tracking.py
  src/repository/order_classification/order_classification_config_repository.py
  src/scheme/order_classification/order_classification_scheme.py
Labels: PROD

#340 hotfix: change time formatting in new order message
  src/infra/domyland/orders.py
  src/model/order_tracking/task_tracking_model.py
  src/util/format_timestamp_to_huma_readable.py
Labels: PROD

#342 feat: add enriched order data to sla_ping_message
  src/infra/domyland/orders.py
  src/model/order_tracking/actions/new_order_message.py
  src/model/order_tracking/actions/sla_ping_message.py
  src/model/order_tracking/task_tracking_model.py
  src/util/format_timestamp_to_human_readable.py
Labels: PROD

#343 Order tracking tasks manager optimization
  docker-compose.yml
  poetry.lock
  pyproject.toml
  src/controller/order_classification/vysota/order_classification_controller.py
  src/infra/async_database.py
  src/infra/database.py
  src/infra/domyland/auth.py
  src/infra/domyland/base.py
  src/infra/domyland/chat.py
  src/infra/domyland/order.py
  src/infra/domyland/order_status.py
  src/infra/domyland/orders.py
  src/infra/env.py
  src/kafka/consumer/order_chat_message_sending.py
  src/kafka/helpers/telegram_message_helper.py
  src/middleware/error_handle_middleware.py
  src/model/base.py
  src/model/order_classification/order_classification_config_model.py
  src/model/order_classification/order_classification_model.py
  src/model/order_notification/order_notification_model.py
  src/model/order_tracking/actions/new_order_message.py
  src/model/order_tracking/actions/sla_ping_message.py
  src/model/order_tracking/helpers/message_order_params.py
  src/model/order_tracking/task_tracking_model.py
  src/orders_tasks_tracking.py
  src/repository/base.py
  src/repository/order_classification/order_classification_config_repository.py
  src/repository/order_tracking/order_tracking_task_repository.py
  src/scheme/order_classification/order_classification_scheme.py
  src/scheme/order_tracking/message_order_params_schema.py
  src/util/datetimes_formats.py
  src/util/format_timestamp_to_human_readable.py
  src/util/seconds_to_time_str.py
  src/util/validation.py
Labels: WIP

#344 Order Tracking Tasks Optimization (async)
  docker-compose.yml
  poetry.lock
  pyproject.toml
  src/controller/order_classification/vysota/order_classification_controller.py
  src/infra/async_database.py
  src/infra/database.py
  src/infra/domyland/auth.py
  src/infra/domyland/base.py
  src/infra/domyland/chat.py
  src/infra/domyland/order.py
  src/infra/domyland/order_status.py
  src/infra/domyland/orders.py
  src/infra/env.py
  src/kafka/consumer/order_chat_message_sending.py
  src/kafka/helpers/telegram_message_helper.py
  src/middleware/error_handle_middleware.py
  src/model/base.py
  src/model/order_classification/order_classification_config_model.py
  src/model/order_classification/order_classification_model.py
  src/model/order_notification/order_notification_model.py
  src/model/order_tracking/actions/new_order_message.py
  src/model/order_tracking/actions/sla_ping_message.py
  src/model/order_tracking/helpers/message_order_params.py
  src/model/order_tracking/task_tracking_model.py
  src/orders_tasks_tracking.py
  src/repository/base.py
  src/repository/order_classification/order_classification_config_repository.py
  src/repository/order_tracking/order_tracking_task_repository.py
  src/scheme/order_classification/order_classification_scheme.py
  src/scheme/order_tracking/message_order_params_schema.py
  src/util/datetimes_formats.py
  src/util/format_timestamp_to_human_readable.py
  src/util/seconds_to_time_str.py
  src/util/validation.py
Labels: PROD

#345 fix: datetimes with timezone in order tracking tasks
  src/infra/order_tracking/action.py
  src/migrations/versions/478f4f152397_orders_tracking_tasks.py
  src/scheme/order_tracking/order_tracking_task_scheme.py
Labels: PROD

#348 hotfix: responsible users for emergency orders
  src/model/order_classification/order_classification_model.py
Labels: PROD
